namespace Echoes.API.Models.Enums
{
    // EVE-style location flags (like eveflags.txt)
    public enum ItemLocationFlag : int
    {
        None = 0,
        Hangar = 1,
        Cargo = 2,
        LowSlot0 = 11,
        LowSlot1 = 12,
        LowSlot2 = 13,
        LowSlot3 = 14,
        LowSlot4 = 15,
        LowSlot5 = 16,
        LowSlot6 = 17,
        LowSlot7 = 18,
        MedSlot0 = 19,
        MedSlot1 = 20,
        MedSlot2 = 21,
        MedSlot3 = 22,
        MedSlot4 = 23,
        MedSlot5 = 24,
        MedSlot6 = 25,
        MedSlot7 = 26,
        HighSlot0 = 27,
        HighSlot1 = 28,
        HighSlot2 = 29,
        HighSlot3 = 30,
        HighSlot4 = 31,
        HighSlot5 = 32,
        HighSlot6 = 33,
        HighSlot7 = 34,
        DroneBay = 90,
        ShipHangar = 93,
        Skill = 101,
        Implant = 113,
    }

    public enum ItemGroup : int
    {
        Ship = 1,
        Module = 2,
        Charge = 3,
        Blueprint = 4,
        Commodity = 5,
        Drone = 6,
        Implant = 7,
        Deployable = 8,
        Structure = 9,
        Asteroid = 10,
        Skill = 11,
        Frigate = 12,
        Cruiser = 13,
        Battleship = 14,
        Industrial = 15,
        Capital = 16,
        HighPowerModule = 17,
        MediumPowerModule = 18,
        LowPowerModule = 19,
        Rig = 20,
        Subsystem = 21,
        Mineral = 22,
        Gas = 23,
        Ice = 24,
        MoonMaterial = 25,
        PlanetMaterial = 26,
    }
}