// <auto-generated />
using System;
using Echoes.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Echoes.API.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260104234937_AddServerMetadata")]
    partial class AddServerMetadata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Echoes.API.Models.Entities.Character.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeveloper")
                        .HasColumnType("boolean");

                    b.Property<string>("LastIP")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastLogout")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("bytea");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("Echoes.API.Models.Entities.Character.AccountBan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BannedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("BannedById")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("BannedById");

                    b.ToTable("account_bans");
                });

            modelBuilder.Entity("Echoes.API.Models.Entities.Character.AccountSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastActivity")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("RefreshTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SessionToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CharacterId");

                    b.ToTable("AccountSessions", (string)null);
                });

            modelBuilder.Entity("Echoes.API.Models.Entities.Character.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<long?>("ActiveShipItemId")
                        .HasColumnType("bigint");

                    b.Property<int>("AncestryId")
                        .HasColumnType("integer");

                    b.Property<int>("BloodlineId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CloneExpiration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CorporationId")
                        .HasColumnType("uuid");

                    b.Property<long>("CorporationRole")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("InWarp")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDocked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMain")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastLogin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("RaceId")
                        .HasColumnType("integer");

                    b.Property<float>("SecurityStatus")
                        .HasColumnType("real");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("SkillTrainingEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalSkillPoints")
                        .HasColumnType("integer");

                    b.Property<int>("UnallocatedSkillPoints")
                        .HasColumnType("integer");

                    b.Property<long>("WalletBalance")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ActiveShipItemId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Characters", (string)null);
                });

            modelBuilder.Entity("Echoes.API.Models.Entities.Character.CharacterImplant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<int>("Slot")
                        .HasColumnType("integer");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("character_implants");
                });

            modelBuilder.Entity("Echoes.API.Models.Entities.Character.CharacterLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<bool>("InWarp")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCloaked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDocked")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUpdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("LocationType")
                        .HasColumnType("integer");

                    b.Property<double>("PositionX")
                        .HasColumnType("double precision");

                    b.Property<double>("PositionY")
                        .HasColumnType("double precision");

                    b.Property<double>("PositionZ")
                        .HasColumnType("double precision");

                    b.Property<float>("RotationW")
                        .HasColumnType("real");

                    b.Property<float>("RotationX")
                        .HasColumnType("real");

                    b.Property<float>("RotationY")
                        .HasColumnType("real");

                    b.Property<float>("RotationZ")
                        .HasColumnType("real");

                    b.Property<long?>("ShipItemId")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("SolarSystemId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("StationId")
                        .HasColumnType("uuid");

                    b.Property<float>("VelocityX")
                        .HasColumnType("real");

                    b.Property<float>("VelocityY")
                        .HasColumnType("real");

                    b.Property<float>("VelocityZ")
                        .HasColumnType("real");

                    b.Property<DateTime?>("WarpEndTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId")
                        .IsUnique();

                    b.HasIndex("ShipItemId");

                    b.HasIndex("SolarSystemId");

                    b.HasIndex("StationId");

                    b.ToTable("CharacterLocations", (string)null);
                });

            modelBuilder.Entity("Echoes.API.Models.Entities.Character.CharacterSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer");

                    b.Property<int>("Skillpoints")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TrainingEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("TrainingStart")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("character_skills");
                });

            modelBuilder.Entity("Echoes.API.Models.Entities.Character.CharacterStanding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<float>("Standing")
                        .HasColumnType("real");

                    b.Property<int>("TargetId")
                        .HasColumnType("integer");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("character_standings");
                });

            modelBuilder.Entity("Echoes.API.Models.Entities.GameServer.GameServerNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("CPUUsage")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GamePort")
                        .HasColumnType("integer");

                    b.Property<string>("GameVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("GeoRegion")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Hostname")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("InstanceId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastHeartbeat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("integer");

                    b.Property<long>("MemoryUsageMB")
                        .HasColumnType("bigint");

                    b.Property<float>("NetworkInKbps")
                        .HasColumnType("real");

                    b.Property<float>("NetworkOutKbps")
                        .HasColumnType("real");

                    b.Property<int>("OnlinePlayers")
                        .HasColumnType("integer");

                    b.Property<string>("PublicIP")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<Guid?>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ServerTags")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("SolarSystemId")
                        .HasColumnType("uuid");

                    b.Property<string>("StartupArguments")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WebPort")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.HasIndex("SolarSystemId")
                        .IsUnique();

                    b.ToTable("game_servers");
                });

            modelBuilder.Entity("Echoes.API.Models.Entities.Inventory.InventoryItem", b =>
                {
                    b.Property<long>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ItemId"));

                    b.Property<Guid?>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsSingleton")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer");

                    b.HasKey("ItemId");

                    b.HasIndex("CharacterId");

                    b.ToTable("inventory_items");
                });

            modelBuilder.Entity("Echoes.API.Models.Entities.Universe.AsteroidBelt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AsteroidCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("Density")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("PositionX")
                        .HasColumnType("bigint");

                    b.Property<long>("PositionY")
                        .HasColumnType("bigint");

                    b.Property<long>("PositionZ")
                        .HasColumnType("bigint");

                    b.Property<long>("Radius")
                        .HasColumnType("bigint");

                    b.Property<Guid>("SolarSystemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SolarSystemId");

                    b.ToTable("AsteroidBelts", (string)null);
                });

            modelBuilder.Entity("Echoes.API.Models.Entities.Universe.Constellation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("AverageSecurity")
                        .HasPrecision(3, 2)
                        .HasColumnType("real");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FactionId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("PositionX")
                        .HasColumnType("bigint");

                    b.Property<long>("PositionY")
                        .HasColumnType("bigint");

                    b.Property<long>("PositionZ")
                        .HasColumnType("bigint");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("RegionId");

                    b.ToTable("Constellations", (string)null);
                });

            modelBuilder.Entity("Echoes.API.Models.Entities.Universe.Moon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HasResources")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("OrbitDistance")
                        .HasColumnType("bigint");

                    b.Property<long>("OrbitPeriod")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PlanetId")
                        .HasColumnType("uuid");

                    b.Property<long>("Radius")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PlanetId");

                    b.ToTable("Moons", (string)null);
                });

            modelBuilder.Entity("Echoes.API.Models.Entities.Universe.Planet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("FactionId")
                        .HasColumnType("integer");

                    b.Property<float>("Gravity")
                        .HasColumnType("real");

                    b.Property<bool>("HasAtmosphere")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasMoons")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsColonizable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("OrbitDistance")
                        .HasColumnType("bigint");

                    b.Property<long>("OrbitPeriod")
                        .HasColumnType("bigint");

                    b.Property<long>("PositionX")
                        .HasColumnType("bigint");

                    b.Property<long>("PositionY")
                        .HasColumnType("bigint");

                    b.Property<long>("PositionZ")
                        .HasColumnType("bigint");

                    b.Property<long>("Radius")
                        .HasColumnType("bigint");

                    b.Property<Guid>("SolarSystemId")
                        .HasColumnType("uuid");

                    b.Property<int>("Temperature")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("SolarSystemId");

                    b.ToTable("Planets", (string)null);
                });

            modelBuilder.Entity("Echoes.API.Models.Entities.Universe.PlanetResource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AsteroidBeltId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastHarvested")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MoonId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PlanetId")
                        .HasColumnType("uuid");

                    b.Property<float>("Quality")
                        .HasColumnType("real");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("AsteroidBeltId");

                    b.HasIndex("MoonId");

                    b.HasIndex("PlanetId");

                    b.ToTable("PlanetResources", (string)null);
                });

            modelBuilder.Entity("Echoes.API.Models.Entities.Universe.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("AverageSecurity")
                        .HasPrecision(3, 2)
                        .HasColumnType("real");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("FactionId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("PositionX")
                        .HasColumnType("bigint");

                    b.Property<long>("PositionY")
                        .HasColumnType("bigint");

                    b.Property<long>("PositionZ")
                        .HasColumnType("bigint");

                    b.Property<string>("RegionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UniverseGenerationConfigId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UniverseGenerationConfigId");

                    b.ToTable("Regions", (string)null);
                });

            modelBuilder.Entity("Echoes.API.Models.Entities.Universe.SolarSystem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConstellationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("FactionId")
                        .HasColumnType("integer");

                    b.Property<bool>("HasAsteroidBelts")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasStations")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<float>("Luminosity")
                        .HasPrecision(15, 4)
                        .HasColumnType("real");

                    b.Property<int>("LuminosityClass")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("NumberOfStars")
                        .HasColumnType("integer");

                    b.Property<long>("PositionX")
                        .HasColumnType("bigint");

                    b.Property<long>("PositionY")
                        .HasColumnType("bigint");

                    b.Property<long>("PositionZ")
                        .HasColumnType("bigint");

                    b.Property<long>("Radius")
                        .HasColumnType("bigint");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<float>("SecurityStatus")
                        .HasPrecision(3, 2)
                        .HasColumnType("real");

                    b.Property<float>("SolarMass")
                        .HasPrecision(10, 4)
                        .HasColumnType("real");

                    b.Property<float>("SolarRadius")
                        .HasPrecision(10, 4)
                        .HasColumnType("real");

                    b.Property<int>("StarClass")
                        .HasColumnType("integer");

                    b.Property<int>("Temperature")
                        .HasPrecision(7, 2)
                        .HasColumnType("integer");

                    b.Property<int>("TemperatureClass")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConstellationId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SecurityStatus");

                    b.HasIndex("PositionX", "PositionY", "PositionZ");

                    b.ToTable("SolarSystems", (string)null);
                });

            modelBuilder.Entity("Echoes.API.Models.Entities.Universe.Stargate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DestinationSolarSystemId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsOperational")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("JumpCost")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("PositionX")
                        .HasColumnType("bigint");

                    b.Property<long>("PositionY")
                        .HasColumnType("bigint");

                    b.Property<long>("PositionZ")
                        .HasColumnType("bigint");

                    b.Property<Guid>("SourceSolarSystemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DestinationSolarSystemId");

                    b.HasIndex("SourceSolarSystemId");

                    b.ToTable("Stargates", (string)null);
                });

            modelBuilder.Entity("Echoes.API.Models.Entities.Universe.Station", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DockingCapacity")
                        .HasColumnType("integer");

                    b.Property<int?>("FactionId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsOperational")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("PositionX")
                        .HasColumnType("bigint");

                    b.Property<long>("PositionY")
                        .HasColumnType("bigint");

                    b.Property<long>("PositionZ")
                        .HasColumnType("bigint");

                    b.Property<string>("Services")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("SolarSystemId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SolarSystemId");

                    b.ToTable("Stations", (string)null);
                });

            modelBuilder.Entity("Echoes.API.Models.Entities.Universe.UniverseGenerationConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Anomalies")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ConfigName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("GenerationStats")
                        .HasColumnType("text");

                    b.Property<long?>("GenerationTimeMs")
                        .HasColumnType("bigint");

                    b.Property<string>("GeneratorVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPreset")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlanetCount")
                        .HasColumnType("integer");

                    b.Property<string>("PresetType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("RandomSeed")
                        .HasColumnType("integer");

                    b.Property<int>("RegionCount")
                        .HasColumnType("integer");

                    b.Property<int>("SeedVersion")
                        .HasColumnType("integer");

                    b.Property<int>("SystemCount")
                        .HasColumnType("integer");

                    b.Property<string>("Tags")
                        .HasColumnType("text");

                    b.Property<string>("UniverseSeed")
                        .HasColumnType("text");

                    b.Property<int>("UsageCount")
                        .HasColumnType("integer");

                    b.Property<bool>("UseSeedBasedGeneration")
                        .HasColumnType("boolean");

                    b.Property<string>("Wormholes")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.ToTable("universe_generation_configs");
                });

            modelBuilder.Entity("Echoes.Server.Models.Entities.Universe.Anomaly", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<double>("CurrentDurability")
                        .HasColumnType("double precision")
                        .HasColumnName("current_durability");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("difficulty");

                    b.Property<double>("Durability")
                        .HasColumnType("double precision")
                        .HasColumnName("durability");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<long>("PositionX")
                        .HasColumnType("bigint")
                        .HasColumnName("position_x");

                    b.Property<long>("PositionY")
                        .HasColumnType("bigint")
                        .HasColumnName("position_y");

                    b.Property<long>("PositionZ")
                        .HasColumnType("bigint")
                        .HasColumnName("position_z");

                    b.Property<double>("Radius")
                        .HasColumnType("double precision")
                        .HasColumnName("radius");

                    b.Property<string>("RewardData")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reward_data");

                    b.Property<int>("ScanStrength")
                        .HasColumnType("integer")
                        .HasColumnName("scan_strength");

                    b.Property<string>("Signature")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("signature");

                    b.Property<Guid>("SolarSystemId")
                        .HasColumnType("uuid")
                        .HasColumnName("solar_system_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Difficulty");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Signature")
                        .IsUnique();

                    b.HasIndex("SolarSystemId");

                    b.HasIndex("Type");

                    b.ToTable("Anomalies", (string)null);
                });

            modelBuilder.Entity("Echoes.Server.Models.Entities.Universe.Wormhole", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("class");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsExitOnly")
                        .HasColumnType("boolean")
                        .HasColumnName("is_exit_only");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<double>("MaxMass")
                        .HasPrecision(18, 2)
                        .HasColumnType("double precision")
                        .HasColumnName("max_mass");

                    b.Property<string>("MaxShipSize")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("max_ship_size");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<Guid?>("PairedWormholeId")
                        .HasColumnType("uuid")
                        .HasColumnName("paired_wormhole_id");

                    b.Property<long>("PositionX")
                        .HasColumnType("bigint")
                        .HasColumnName("position_x");

                    b.Property<long>("PositionY")
                        .HasColumnType("bigint")
                        .HasColumnName("position_y");

                    b.Property<long>("PositionZ")
                        .HasColumnType("bigint")
                        .HasColumnName("position_z");

                    b.Property<double>("Radius")
                        .HasColumnType("double precision")
                        .HasColumnName("radius");

                    b.Property<double>("RemainingMass")
                        .HasPrecision(18, 2)
                        .HasColumnType("double precision")
                        .HasColumnName("remaining_mass");

                    b.Property<string>("Signature")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("signature");

                    b.Property<Guid>("SourceSystemId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_system_id");

                    b.Property<double>("Stability")
                        .HasPrecision(3, 2)
                        .HasColumnType("double precision")
                        .HasColumnName("stability");

                    b.Property<Guid>("TargetSystemId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_system_id");

                    b.Property<int>("TotalPasses")
                        .HasColumnType("integer")
                        .HasColumnName("total_passes");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("PairedWormholeId")
                        .IsUnique();

                    b.HasIndex("Signature")
                        .IsUnique();

                    b.HasIndex("SourceSystemId");

                    b.HasIndex("TargetSystemId");

                    b.ToTable("wormholes");
                });

            modelBuilder.Entity("Echoes.API.Models.Entities.Character.AccountBan", b =>
                {
                    b.HasOne("Echoes.API.Models.Entities.Character.Account", "Account")
                        .WithMany("Bans")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Echoes.API.Models.Entities.Character.Character", "BannedBy")
                        .WithMany()
                        .HasForeignKey("BannedById");

                    b.Navigation("Account");

                    b.Navigation("BannedBy");
                });

            modelBuilder.Entity("Echoes.API.Models.Entities.Character.AccountSession", b =>
                {
                    b.HasOne("Echoes.API.Models.Entities.Character.Account", "Account")
                        .WithMany("Sessions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Echoes.API.Models.Entities.Character.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Echoes.API.Models.Entities.Character.Character", b =>
                {
                    b.HasOne("Echoes.API.Models.Entities.Character.Account", "Account")
                        .WithMany("Characters")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Echoes.API.Models.Entities.Inventory.InventoryItem", "ActiveShip")
                        .WithMany()
                        .HasForeignKey("ActiveShipItemId");

                    b.Navigation("Account");

                    b.Navigation("ActiveShip");
                });

            modelBuilder.Entity("Echoes.API.Models.Entities.Character.CharacterImplant", b =>
                {
                    b.HasOne("Echoes.API.Models.Entities.Character.Character", "Character")
                        .WithMany("Implants")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Echoes.API.Models.Entities.Character.CharacterLocation", b =>
                {
                    b.HasOne("Echoes.API.Models.Entities.Character.Character", "Character")
                        .WithOne("CurrentLocation")
                        .HasForeignKey("Echoes.API.Models.Entities.Character.CharacterLocation", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Echoes.API.Models.Entities.Inventory.InventoryItem", "Ship")
                        .WithMany()
                        .HasForeignKey("ShipItemId");

                    b.HasOne("Echoes.API.Models.Entities.Universe.SolarSystem", "SolarSystem")
                        .WithMany()
                        .HasForeignKey("SolarSystemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Echoes.API.Models.Entities.Universe.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Character");

                    b.Navigation("Ship");

                    b.Navigation("SolarSystem");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("Echoes.API.Models.Entities.Character.CharacterSkill", b =>
                {
                    b.HasOne("Echoes.API.Models.Entities.Character.Character", "Character")
                        .WithMany("Skills")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Echoes.API.Models.Entities.Character.CharacterStanding", b =>
                {
                    b.HasOne("Echoes.API.Models.Entities.Character.Character", "Character")
                        .WithMany("Standings")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Echoes.API.Models.Entities.GameServer.GameServerNode", b =>
                {
                    b.HasOne("Echoes.API.Models.Entities.Universe.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId");

                    b.HasOne("Echoes.API.Models.Entities.Universe.SolarSystem", "SolarSystem")
                        .WithOne("PrimaryServer")
                        .HasForeignKey("Echoes.API.Models.Entities.GameServer.GameServerNode", "SolarSystemId");

                    b.Navigation("Region");

                    b.Navigation("SolarSystem");
                });

            modelBuilder.Entity("Echoes.API.Models.Entities.Inventory.InventoryItem", b =>
                {
                    b.HasOne("Echoes.API.Models.Entities.Character.Character", null)
                        .WithMany("InventoryItems")
                        .HasForeignKey("CharacterId");
                });

            modelBuilder.Entity("Echoes.API.Models.Entities.Universe.AsteroidBelt", b =>
                {
                    b.HasOne("Echoes.API.Models.Entities.Universe.SolarSystem", "SolarSystem")
                        .WithMany("AsteroidBelts")
                        .HasForeignKey("SolarSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SolarSystem");
                });

            modelBuilder.Entity("Echoes.API.Models.Entities.Universe.Constellation", b =>
                {
                    b.HasOne("Echoes.API.Models.Entities.Universe.Region", "Region")
                        .WithMany("Constellations")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Echoes.API.Models.Entities.Universe.Moon", b =>
                {
                    b.HasOne("Echoes.API.Models.Entities.Universe.Planet", "Planet")
                        .WithMany("Moons")
                        .HasForeignKey("PlanetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Planet");
                });

            modelBuilder.Entity("Echoes.API.Models.Entities.Universe.Planet", b =>
                {
                    b.HasOne("Echoes.API.Models.Entities.Universe.SolarSystem", "SolarSystem")
                        .WithMany("Planets")
                        .HasForeignKey("SolarSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SolarSystem");
                });

            modelBuilder.Entity("Echoes.API.Models.Entities.Universe.PlanetResource", b =>
                {
                    b.HasOne("Echoes.API.Models.Entities.Universe.AsteroidBelt", "AsteroidBelt")
                        .WithMany("Resources")
                        .HasForeignKey("AsteroidBeltId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Echoes.API.Models.Entities.Universe.Moon", "Moon")
                        .WithMany("Resources")
                        .HasForeignKey("MoonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Echoes.API.Models.Entities.Universe.Planet", "Planet")
                        .WithMany("Resources")
                        .HasForeignKey("PlanetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("AsteroidBelt");

                    b.Navigation("Moon");

                    b.Navigation("Planet");
                });

            modelBuilder.Entity("Echoes.API.Models.Entities.Universe.Region", b =>
                {
                    b.HasOne("Echoes.API.Models.Entities.Universe.UniverseGenerationConfig", null)
                        .WithMany("Regions")
                        .HasForeignKey("UniverseGenerationConfigId");
                });

            modelBuilder.Entity("Echoes.API.Models.Entities.Universe.SolarSystem", b =>
                {
                    b.HasOne("Echoes.API.Models.Entities.Universe.Constellation", "Constellation")
                        .WithMany("SolarSystems")
                        .HasForeignKey("ConstellationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Constellation");
                });

            modelBuilder.Entity("Echoes.API.Models.Entities.Universe.Stargate", b =>
                {
                    b.HasOne("Echoes.API.Models.Entities.Universe.SolarSystem", "DestinationSolarSystem")
                        .WithMany()
                        .HasForeignKey("DestinationSolarSystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Echoes.API.Models.Entities.Universe.SolarSystem", "SourceSolarSystem")
                        .WithMany("Stargates")
                        .HasForeignKey("SourceSolarSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DestinationSolarSystem");

                    b.Navigation("SourceSolarSystem");
                });

            modelBuilder.Entity("Echoes.API.Models.Entities.Universe.Station", b =>
                {
                    b.HasOne("Echoes.API.Models.Entities.Universe.SolarSystem", "SolarSystem")
                        .WithMany("Stations")
                        .HasForeignKey("SolarSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SolarSystem");
                });

            modelBuilder.Entity("Echoes.Server.Models.Entities.Universe.Anomaly", b =>
                {
                    b.HasOne("Echoes.API.Models.Entities.Universe.SolarSystem", "SolarSystem")
                        .WithMany("Anomalies")
                        .HasForeignKey("SolarSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SolarSystem");
                });

            modelBuilder.Entity("Echoes.Server.Models.Entities.Universe.Wormhole", b =>
                {
                    b.HasOne("Echoes.Server.Models.Entities.Universe.Wormhole", "PairedWormhole")
                        .WithOne()
                        .HasForeignKey("Echoes.Server.Models.Entities.Universe.Wormhole", "PairedWormholeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Echoes.API.Models.Entities.Universe.SolarSystem", "SourceSystem")
                        .WithMany("SourceWormholes")
                        .HasForeignKey("SourceSystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Echoes.API.Models.Entities.Universe.SolarSystem", "TargetSystem")
                        .WithMany("TargetWormholes")
                        .HasForeignKey("TargetSystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PairedWormhole");

                    b.Navigation("SourceSystem");

                    b.Navigation("TargetSystem");
                });

            modelBuilder.Entity("Echoes.API.Models.Entities.Character.Account", b =>
                {
                    b.Navigation("Bans");

                    b.Navigation("Characters");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Echoes.API.Models.Entities.Character.Character", b =>
                {
                    b.Navigation("CurrentLocation");

                    b.Navigation("Implants");

                    b.Navigation("InventoryItems");

                    b.Navigation("Skills");

                    b.Navigation("Standings");
                });

            modelBuilder.Entity("Echoes.API.Models.Entities.Universe.AsteroidBelt", b =>
                {
                    b.Navigation("Resources");
                });

            modelBuilder.Entity("Echoes.API.Models.Entities.Universe.Constellation", b =>
                {
                    b.Navigation("SolarSystems");
                });

            modelBuilder.Entity("Echoes.API.Models.Entities.Universe.Moon", b =>
                {
                    b.Navigation("Resources");
                });

            modelBuilder.Entity("Echoes.API.Models.Entities.Universe.Planet", b =>
                {
                    b.Navigation("Moons");

                    b.Navigation("Resources");
                });

            modelBuilder.Entity("Echoes.API.Models.Entities.Universe.Region", b =>
                {
                    b.Navigation("Constellations");
                });

            modelBuilder.Entity("Echoes.API.Models.Entities.Universe.SolarSystem", b =>
                {
                    b.Navigation("Anomalies");

                    b.Navigation("AsteroidBelts");

                    b.Navigation("Planets");

                    b.Navigation("PrimaryServer");

                    b.Navigation("SourceWormholes");

                    b.Navigation("Stargates");

                    b.Navigation("Stations");

                    b.Navigation("TargetWormholes");
                });

            modelBuilder.Entity("Echoes.API.Models.Entities.Universe.UniverseGenerationConfig", b =>
                {
                    b.Navigation("Regions");
                });
#pragma warning restore 612, 618
        }
    }
}
