using System.ComponentModel.DataAnnotations;

namespace Echoes.API.Models.DTOs.Server
{
    /// <summary>
    /// Request DTO for registering a new game server instance.
    /// Used when a game server starts up and needs to register itself with the backend.
    /// </summary>
    public class RegisterServerRequestDto
    {
        /// <summary>
        /// Unique identifier for this server instance.
        /// Should be generated by the game server on startup.
        /// </summary>
        [Required]
        [MaxLength(50)]
        public string InstanceId { get; set; } = string.Empty;

        /// <summary>
        /// Public IP address where the game server can be reached by clients.
        /// </summary>
        [Required]
        [MaxLength(45)]
        public string PublicIP { get; set; } = "127.0.0.1";

        /// <summary>
        /// Port number for game client connections.
        /// </summary>
        [Required]
        [Range(1, 65535)]
        public int GamePort { get; set; } = 7777;

        /// <summary>
        /// Port number for web/API connections to the game server.
        /// </summary>
        [Required]
        [Range(1, 65535)]
        public int WebPort { get; set; } = 7778;

        /// <summary>
        /// Optional: Solar System ID if this is a dedicated server for a specific system.
        /// Mutually exclusive with RegionId for dedicated system servers.
        /// </summary>
        public Guid? SolarSystemId { get; set; }

        /// <summary>
        /// Optional: Region ID if this is a regional cluster server handling multiple systems.
        /// Regional servers can handle multiple solar systems within their region.
        /// </summary>
        public Guid? RegionId { get; set; }

        /// <summary>
        /// Maximum number of concurrent players this server can handle.
        /// </summary>
        [Required]
        [Range(1, 10000)]
        public int MaxPlayers { get; set; } = 100;

        /// <summary>
        /// Geographic region code for this server (e.g., "EU", "US", "ASIA").
        /// Used for geographic load balancing.
        /// </summary>
        [MaxLength(10)]
        public string? GeoRegion { get; set; } = "EU";

        /// <summary>
        /// Game version running on this server.
        /// Used to ensure version compatibility.
        /// </summary>
        [MaxLength(20)]
        public string? GameVersion { get; set; } = "1.0.0";

        /// <summary>
        /// Hostname of the machine running the server.
        /// </summary>
        [MaxLength(100)]
        public string? Hostname { get; set; }

        /// <summary>
        /// Comma-separated tags for server filtering and categorization.
        /// Example: "pvp,hardcore,events"
        /// </summary>
        [MaxLength(200)]
        public string? ServerTags { get; set; }

        /// <summary>
        /// Validates that required server registration data is provided.
        /// </summary>
        /// <exception cref="ArgumentException">Thrown when validation fails.</exception>
        public void Validate()
        {
            if (string.IsNullOrWhiteSpace(InstanceId))
                throw new ArgumentException("InstanceId is required");

            if (string.IsNullOrWhiteSpace(PublicIP))
                throw new ArgumentException("PublicIP is required");

            if (GamePort <= 0 || GamePort > 65535)
                throw new ArgumentException("Invalid GamePort");

            if (!SolarSystemId.HasValue && !RegionId.HasValue)
                throw new ArgumentException("Must specify either SolarSystemId (Dedicated) or RegionId (Cluster)");
        }
    }
}
